apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend
  labels:
    app: k8s-backend
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: k8s-backend
        image: phiroict/k8s-test-backend@sha256:0bd970c100bee814b327081e554a7d58cba774e3b233b155017d23cbae64e0b4
        env:
        - name: ENV_SET
          value: nonprod
