apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend
  labels:
    app: k8s-backend
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: k8s-backend
        image: phiroict/k8s-test-backend@sha256:57c13b315cb50d1f841addf1ea388f184886c2a35b9100428dad5668267eb633
        env:
        - name: ENV_SET
          value: nonprod
