apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend
  labels:
    app: k8s-backend
spec:
  template:
    spec:
      containers:
      - name: k8s-backend
        image: phiroict/k8s-test-backend@sha256:3938c19ed82fc9890747ce4646aadc6f1bc839e4728912789f2454b071c7baf4
        env:
        - name: ENV_SET
          value: dev
